/*
SELECT * FROM DEPT;
*/
/*
SELECT ENAME|| ', '||JOB AS "             Employer", 12*SAL "details" FROM EMP;
*/
/*
SELECT ENAME, SAL FROM EMP
WHERE SAL NOT BETWEEN '1500' AND '2850';
*/
/*
SELECT ENAME, JOB, EMPNO FROM EMP
WHERE (EMPNO = '1111') OR (EMPNO = '2222') OR (EMPNO = '3333');
*/
/*
SELECT ENAME FROM EMP
WHERE ENAME LIKE '_A%';
*/
/*
SELECT ENAME, '*'||SAL AS SAL, EMPNO FROM EMP
WHERE ENAME LIKE '______';
*/
/*
SELECT ENAME, ROUND(MONTHS_BETWEEN(SYSDATE, HIREDATE)) AS MONTHS FROM EMP
ORDER BY HIREDATE ASC;
*/
/*
SELECT ENAME, SAL, COMM, NVL(COMM+(12*SAL), SAL) FROM EMP;
*/
/*
SELECT ENAME, DECODE(COMM, NULL, 'No commisions', COMM) AS COMM FROM EMP;
*/
/*
SELECT DISTINCT e.JOB AS JOB FROM EMP e, DEPT d
WHERE (d.DEPTNO = 30) AND (e.DEPTNO = d.DEPTNO);
*/
/*
SELECT e.ENAME, e.JOB, d.DEPTNO, d.LOC FROM EMP e, DEPT d
WHERE (d.LOC = 'DALLAS') AND (e.DEPTNO = d.DEPTNO);
*/
/*
SELECT m.ENAME||' - > '||m.ENAME FROM EMP w, EMP m
WHERE w.MGR = m.EMPNO;
*/
/*
SELECT d.DNAME, d.DEPTNO, DECODE(e.DEPTNO, NULL, '',
                                           e.ENAME||' '||e.EMPNO) EMP
FROM EMP e, DEPT d
WHERE e.DEPTNO (+)= d.DEPTNO;
*/
/*
SELECT e.ENAME, e.SAL, s.GRADE FROM EMP e, SALGRADE s
WHERE e.SAL BETWEEN s.LOSAL AND s.HISAL;
*/
/*
SELECT ENAME FROM EMP
WHERE ENAME LIKE '_~%%' ESCAPE '~';
*/